-- begin UNTITLED9_EMPLOYEE
alter table UNTITLED9_EMPLOYEE add constraint FK_UNTITLED9_EMPLOYEE_ON_CATEGORY_OF_PRODUCTS foreign key (CATEGORY_OF_PRODUCTS_ID) references UNTITLED9_CATEGORY_OF_PRODUCTS(ID)^
alter table UNTITLED9_EMPLOYEE add constraint FK_UNTITLED9_EMPLOYEE_ON_PRODUCTS foreign key (PRODUCTS_ID) references UNTITLED9_PRODUCTS(ID)^
create index IDX_UNTITLED9_EMPLOYEE_ON_CATEGORY_OF_PRODUCTS on UNTITLED9_EMPLOYEE (CATEGORY_OF_PRODUCTS_ID)^
create index IDX_UNTITLED9_EMPLOYEE_ON_PRODUCTS on UNTITLED9_EMPLOYEE (PRODUCTS_ID)^
-- end UNTITLED9_EMPLOYEE
-- begin UNTITLED9_PRODUCTS
alter table UNTITLED9_PRODUCTS add constraint FK_UNTITLED9_PRODUCTS_ON_CATEGORY_OF_PRODUCTS foreign key (CATEGORY_OF_PRODUCTS_ID) references UNTITLED9_CATEGORY_OF_PRODUCTS(ID)^
create index IDX_UNTITLED9_PRODUCTS_ON_CATEGORY_OF_PRODUCTS on UNTITLED9_PRODUCTS (CATEGORY_OF_PRODUCTS_ID)^
-- end UNTITLED9_PRODUCTS
